name: Build and test

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash


env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dmg: [no_dmg]
        #include:
        #  - os: macos-latest
        #    dmg: dmg
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      # This is needed because the GMP crate does not support MSVC
    - name: Install MINGW version of rust for Windows
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable-x86_64-pc-windows-gnu
          target: x86_64-pc-windows-gnu
          override: true
          default: true
    - name: Install SWI Prolog on Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-add-repository ppa:swi-prolog/stable
        sudo apt-get update
        sudo apt install swi-prolog-nox
    - name: Install LLVM and SWI Prolog on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: choco install llvm swi-prolog
    - name: Install SWI Prolog on MacOS from brew
      if: ${{ matrix.os == 'macos-latest' && matrix.dmg == 'no_dmg' }}
      run: brew install swi-prolog
    - name: Install SWI Prolog on MacOS from dmg
      if: ${{ matrix.os == 'macos-latest' && matrix.dmg == 'dmg' }}
      run: bash .ci/install_swipl_dmg.sh
    - name: Print information with swipl-info on posix
      if: ${{ matrix.os != 'windows-latest' && matrix.dmg == 'no_dmg' }}
      run: cargo run --bin print_swipl_info
    - name: Print information with swipl-info on windows
      if: ${{ matrix.os == 'windows-latest' }}
      env: 
        SWIPL: C:\Program Files\swipl\bin\swipl.exe
      run: cargo run --bin print_swipl_info
    - name: Print information with swipl-info on osx with dmg
      if: ${{ matrix.dmg == 'dmg' }}
      env: 
        SWIPL: /Applications/SWI-Prolog.app/Contents/MacOS/swipl
      run: cargo run --bin print_swipl_info
    - name: Install cargo-swipl
      run: cargo install --path ./cargo-swipl
    - name: Run tests on posix
      if: ${{ matrix.os != 'windows-latest' && matrix.dmg == 'no_dmg' }}
      run: cargo swipl test --all-features

    - name: Install msys2
      if: ${{ matrix.os == 'windows-latest' }}
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          diffutils
          m4
          make
          mingw-w64-x86_64-gcc
          mingw-w64-gmp
    - name: Run tests on windows
      if: ${{ matrix.os == 'windows-latest' }}
      shell: msys2 {0}
      env:
        SWIPL: C:\Program Files\swipl\bin\swipl.exe
        LIBCLANG_PATH: C:\Program Files\LLVM\bin\
      run: |
        export PATH="$PATH:/c/Users/Default/.cargo/bin"
        cargo swipl test --all-features --target=x86_64-pc-windows-gnu

    - name: Run tests on osx with dmg
      if: ${{ matrix.dmg == 'dmg' }}
      env: 
        SWIPL: /Applications/SWI-Prolog.app/Contents/MacOS/swipl
      run: cargo swipl test --all-features
