name: Build and test

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash


env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dmg: [no_dmg]
        #include:
        #  - os: macos-latest
        #    dmg: dmg
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install SWI Prolog on Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-add-repository ppa:swi-prolog/stable
        sudo apt-get update
        sudo apt install swi-prolog-nox
    - name: Install LLVM and SWI Prolog on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: choco install llvm swi-prolog
    - name: Install SWI Prolog on MacOS from brew
      if: ${{ matrix.os == 'macos-latest' && matrix.dmg == 'no_dmg' }}
      run: brew install swi-prolog
    - name: Install SWI Prolog on MacOS from dmg
      if: ${{ matrix.os == 'macos-latest' && matrix.dmg == 'dmg' }}
      run: bash .ci/install_swipl_dmg.sh
    - name: Print information with swipl-info on posix
      if: ${{ matrix.os != 'windows-latest' && matrix.dmg == 'no_dmg' }}
      run: cargo run --bin print_swipl_info
    - name: Print information with swipl-info on windows
      if: ${{ matrix.os == 'windows-latest' }}
      env: 
        SWIPL: C:\Program Files\swipl\bin\swipl.exe
      run: cargo run --bin print_swipl_info
    - name: Print information with swipl-info on osx with dmg
      if: ${{ matrix.dmg == 'dmg' }}
      env: 
        SWIPL: /Applications/SWI-Prolog.app/Contents/MacOS/swipl
      run: cargo run --bin print_swipl_info
    - name: Install cargo-swipl
      run: cargo install --path ./cargo-swipl
    - name: Run tests on posix
      if: ${{ matrix.os != 'windows-latest' && matrix.dmg == 'no_dmg' }}
      run: cargo swipl test --all-features
    - name: Run tests on windows
      if: ${{ matrix.os == 'windows-latest' }}
      env: 
        SWIPL: C:\Program Files\swipl\bin\swipl.exe
        LIBCLANG_PATH: C:\Program Files\LLVM\bin\
      run: cargo swipl test --all-features
    - name: Run tests on osx with dmg
      if: ${{ matrix.dmg == 'dmg' }}
      env: 
        SWIPL: /Applications/SWI-Prolog.app/Contents/MacOS/swipl
      run: cargo swipl test --all-features

    build_arm64:
      # Still a seperate job until GitHub actions supports arm64 natively
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run tests on arm64
        id: build
        with:
          arch: aarch64
          distro: ubuntu_latest
          dockerRunArgs: |
            --volume "${PWD}:/app"
          run: |
            apt-get update -q -y
            apt-add-repository ppa:swi-prolog/stable
            apt-get update -q -y
            apt install swi-prolog-nox curl -q -y
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source "$HOME/.cargo/env"
            cd /app
            cargo swipl test --all-features
